//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenBay()
        {
            this.Ve = new HashSet<Ve>();
        }
    
        public int ChuyenBayID { get; set; }
        public string SanKhoiHanhID { get; set; }
        public string SanDenID { get; set; }
        public Nullable<System.TimeSpan> GioKhoiHanh { get; set; }
        public Nullable<System.TimeSpan> GioKetThuc { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> SoGheTrong { get; set; }
        public Nullable<int> SoGheVipTrong { get; set; }
        public string TrangThai { get; set; }
    
        public virtual SanBay SanBay { get; set; }
        public virtual SanBay SanBay1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ve { get; set; }

        public Nullable<int> TotalGheTrongAndVip { get { return (int)(SoGheTrong + SoGheVipTrong); } }
    }
}
