//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPMNC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class DBRedNitEntities : DbContext
    {
        public DBRedNitEntities()
            : base("name=DBRedNitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal void UpdateChuyenBayStatus()
        {
            var now = DateTime.Now;

            var chuyenBaysToUpdate = ChuyenBay
                .Where(c => c.NgayKhoiHanh <= now && now <= c.NgayKetThuc && c.GioKhoiHanh <= now.TimeOfDay && c.TrangThai == "Chưa bay")
                .ToList();

            foreach (var chuyenBay in chuyenBaysToUpdate)
            {
                chuyenBay.TrangThai = "Cất cánh";
            }

            SaveChanges();
        }

        public virtual DbSet<AdminUser> AdminUser { get; set; }
        public virtual DbSet<ChuyenBay> ChuyenBay { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<SanBay> SanBay { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ve> Ve { get; set; }
    }
}
