//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public int VeID { get; set; }
        public Nullable<int> ChuyenBayID { get; set; }
        public Nullable<int> KhID { get; set; }
        public Nullable<System.DateTime> NgayDatVe { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string LoaiVe { get; set; }
        public string HangGhe { get; set; }
        public string TrangThaiVe { get; set; }
    
        public virtual ChuyenBay ChuyenBay { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
